# Generated by Django 4.2 on 2023-11-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flore', '0007_alter_family_name_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flore.plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='flore.family'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='flore.genre'),
        ),
    ]
