# Generated by Django 4.2 on 2023-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flore', '0008_alter_image_plant_alter_plant_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='french_name',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
