# Generated by Django 4.2 on 2023-04-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_inpn', models.CharField(default='', max_length=9)),
                ('rank_code', models.CharField(default='', max_length=9)),
                ('family', models.CharField(default='', max_length=100)),
                ('genre', models.CharField(default='', max_length=100)),
                ('scientific_name', models.CharField(default='', max_length=500)),
                ('correct_name', models.CharField(default='', max_length=500)),
                ('french_name', models.CharField(default='', max_length=500)),
                ('author', models.CharField(default='', max_length=100)),
                ('publ_year', models.CharField(default='', max_length=4)),
                ('eflore_url', models.URLField(default='')),
            ],
            options={
                'ordering': ['scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=500)),
                ('publ_date', models.DateField(default='')),
                ('organ', models.CharField(choices=[('NONE', 'none'), ('FLOWER', 'flower'), ('LEAF', 'leaf'), ('FRUIT', 'fruit'), ('BARK', 'bark'), ('PORT', 'port'), ('BRANCH', 'branch')], default='NONE', max_length=10)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flore.plant')),
            ],
        ),
    ]
