# Generated by Django 4.2 on 2023-04-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flore', '0002_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='eflore_id',
            field=models.CharField(default='', max_length=9),
        ),
    ]
