# Generated by Django 4.2 on 2023-04-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flore', '0003_plant_eflore_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='eflore_id',
            field=models.IntegerField(default=''),
        ),
    ]
