# Generated by Django 4.2 on 2023-04-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flore', '0004_alter_plant_eflore_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='eflore_id',
        ),
    ]
